#!/bin/bash

# DESCRIPTION: RYSCA (direct execution): Escenario simple con 2 PCs y un router (útil para pruebas de desarrollo con librawnet)

LIGHTNING_INSTALLATION_PATH=$(dirname $(readlink -f $(which lightning)))
source $LIGHTNING_INSTALLATION_PATH/functions
source $LIGHTNING_INSTALLATION_PATH/personalized_functions

create_net RedA
create_net RedB
create_net RedR

create_uc3m_host PCA
configure_ip PCA eth1 192.100.100.101/24
configure_ip PCA eth1 fe80::fcfd:ff:fe00:101/64
create_uc3m_host PCB
configure_ip PCB eth1 192.100.100.102/24
configure_ip PCB eth1 fe80::fcfd:ff:fe00:102/64

create_uc3m_router RA routerUC3M
create_uc3m_router RB routerUC3M

connect_machine PCA eth1 RedA
connect_machine PCB eth1 RedB

connect_machine RA eth0.0 RedA
connect_machine RA eth0.1 RedR
connect_machine RB eth0.0 RedB
connect_machine RB eth0.1 RedR

display_host PCA
display_host PCB
display_router RA
display_router RB
